/**
 * Extracts the token layers out of index.html (the board) into portable CSS.
 *
 * The board is the single source of truth. This script guarantees that
 * `tokens/*.css` can never drift from what the board documents.
 *
 *   node tools/build-tokens.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const board = readFileSync(resolve(root, 'index.html'), 'utf8');

/** Pull the first :root { ... } block that follows a given CSS section marker. */
function layerAfter(marker) {
  const at = board.indexOf(marker);
  if (at === -1) throw new Error(`marker not found: ${marker}`);
  const start = board.indexOf(':root {', at);
  if (start === -1) throw new Error(`no :root after marker: ${marker}`);
  let depth = 0, i = board.indexOf('{', start);
  for (let j = i; j < board.length; j++) {
    if (board[j] === '{') depth++;
    else if (board[j] === '}') {
      depth--;
      if (depth === 0) return board.slice(start, j + 1);
    }
  }
  throw new Error(`unterminated :root after marker: ${marker}`);
}

const MARK_PRIM = '01 PRIMITIVE SCALE';
const MARK_SEM = '02 SEMANTIC API';
const MARK_MOTION = '07 MOTION API';

const primitives = layerAfter(MARK_PRIM);
const semantics = layerAfter(MARK_SEM);
const motion = layerAfter(MARK_MOTION);

const banner = (t) => `/* ${'-'.repeat(72)}
   ${t}
   ${'-'.repeat(72)}
   GENERATED by tools/build-tokens.mjs — do not edit by hand.
   Edit index.html instead, then run: node tools/build-tokens.mjs
   Source of truth: DesignTest/index.html
   ${'-'.repeat(72)} */
`;

mkdirSync(resolve(root, 'tokens'), { recursive: true });
mkdirSync(resolve(root, 'adapters'), { recursive: true });

// ---- tokens/primitives.css -------------------------------------------------
writeFileSync(
  resolve(root, 'tokens/primitives.css'),
  banner('LAYER 1 — PRIMITIVES. Raw values, no meaning attached.') +
  `\n/* Do NOT reference these from product code. Use the semantic layer. */\n\n` +
  primitives.replace(':root {', ':root {').replace(/\n\};?\s*$/, '\n}\n') +
  `\n/* Raw scale inventory, for reference and dataviz:\n` +
  `   neutral 0,25,50,100,200,300,400,500,600,700,800,850,900,950\n` +
  `   brand   50,100,200,300,400,500,600,700,800,900\n` +
  `   success warning danger info violet — 100,300,500,700,900 */\n`,
  'utf8'
);

// ---- tokens/semantics-dark.css ---------------------------------------------
writeFileSync(
  resolve(root, 'tokens/semantics-dark.css'),
  banner('LAYER 2 — SEMANTICS (dark theme). The supported contract.') +
  `\n/* Product code references THESE tokens, never the primitives. */\n\n` +
  semantics + '\n\n' +
  `/* Motion — durations, curves, focus halo. See DS-03 Foundations. */\n\n` +
  motion + '\n',
  'utf8'
);

// ---- tokens/index.css ------------------------------------------------------
writeFileSync(
  resolve(root, 'tokens/index.css'),
  banner('DS tokens — single entry point.') +
  `\n/* Usage (framework-agnostic, any stack):\n\n` +
  `   @import "./tokens/index.css";\n\n` +
  `   That single import gives you every primitive, semantic, radius,\n` +
  `   spacing, motion and elevation token in this design system.\n\n` +
  `   Tailwind + shadcn users: see adapters/ instead. */\n\n` +
  `@import "./primitives.css";\n@import "./semantics-dark.css";\n`,
  'utf8'
);

// ---- verification ----------------------------------------------------------
const count = (s) => (s.match(/--[a-z0-9-]+(?=\s*:)/gi) || []).length;
console.log(`primitives.css   ${count(primitives)} custom properties`);
console.log(`semantics-dark   ${count(semantics)} + ${count(motion)} motion`);
console.log(`tokens/index.css written`);
console.log('adapters/ are hand-maintained — see AGENTS.md section 3');
